services:

  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus-container
    volumes:
      - ./metrics/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: always
    network_mode: host
  web:
    build: .
    ports:
      - "8080:8080"