apiVersion: v1
kind: Secret
metadata:
  name: login
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IuZWR1LmNuIjogewoJCQkiYXV0aCI6ICJibXAxTURrNmJtcDFNRGt5TURJeiIKCQl9Cgl9Cn0=