apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: msg
  name: msg
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    path: /actuator/prometheus
    scheme: 'http'
    port: tcp
  namespaceSelector:
    matchNames:
    - nju09
  selector:
    matchLabels:
      app: msg