apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: msg
  name: msg
  namespace: nju09
spec:
  endpoints:
  - interval: 30s
    targetPort: 9090
    path: /actuator/prometheus
  namespaceSelector:
    matchNames:
    - nju09
  selector:
    matchLabels:
      app: msg